
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE user (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  login VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);

CREATE TABLE artifact (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  artifact_type VARCHAR(8) NOT NULL,
  code VARCHAR(17) NOT NULL,
  UNIQUE KEY ARTIFACT_UNIQUE_CODE (code)
);

CREATE TABLE feature (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE feature_artifact(
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  feature_id BIGINT NOT NULL,
  required_artifact_id BIGINT NOT NULL,
  forbidden_artifact_id BIGINT NOT NULL
);